### ISSUE TITLE
login screen go black

### ISSUE THREAD

**Issue by t8go** [SolDoesTech/HyprV4#53]
when i just install the hyprland and login the screen go black for a few second then i was back at the login screen again

**Comment by TeddyHuang-00** [comment]
I was facing similar issue with a fresh install of Arch and this script. I enter the password correctly and then see the black screen for a few seconds before pumped back to the login screen. I suspect this is related to nvidia graphics card support, and maybe a manual install will fix the issue, I hope?

**Comment by TeddyHuang-00** [comment]
Well I've manually gone through the script and make sure nothing is left over, but this doesn't help, so I am guessing some update to certain packages break due to one or more outdated config file content. We need help....

**Comment by TeddyHuang-00** [comment]
I guess this was a similar problem and might be a fix to the problem: https://github.com/SolDoesTech/HyprV4/issues/34

**Comment by psilvaricardo** [comment]
I tried to install hyprland using the provided script and following the YT video for V4 and now I am getting error:

amd gpio invalid config param 0014

and goes to a black screen, it does not let me boot from the arch linux ISO... either from USB or DVD

**Comment by KhushalSharma-dev** [comment]
Something similar happened to me, although my error was related to monitor as per log files.
I defined my monitor type in hyprland.conf (as Sol recommends in HyprV4 Video) which fixed it.

And .... BOOM ! I can use my system again after 6 hours. (It took me a while to understand the issue).

**Comment by bigpennybanks** [comment]
> Something similar happened to me, although my error was related to monitor as per log files. I defined my monitor type in hyprland.conf (as Sol recommends in HyprV4 Video) which fixed it.
> 
> And .... BOOM ! I can use my system again after 6 hours. (It took me a while to understand the issue).

was your issue not being able to log in as well? even when im trying to get the monitor specs/code i get hyprlabd_instance_signature not set (is hyprland running?) error msg. i used dp1 as default but nothing but same problem. not even sure im writing my monitor in right so

**Comment by LazKot** [comment]
Seeing the same problem. Loads perfectly fine up until the login screen. Once the password is put and press enter, screen turns black for 1 second, then switches back to the login screen. Managed to pinpoint the error to after the reboot of installing Nvidia packages.

**Comment by charisvt** [comment]
I'm having the exact same issue on clean setup, however my screen resolution seems to be off. Probably related to that, I will try to fix through config and come back.

**Comment by TeddyHuang-00** [comment]
Found crash report from hyprland in `~/.hyprland/`, don't know if that will help: https://pastebin.com/XBmbGj3G

**Comment by BlakeDotCom** [comment]
The new version of hyprland broke it. My setup was fine but I just updated my packages and it broke, now it crashes after login when trying to go into hyprland.

**Comment by psilvaricardo** [comment]
My setup is fixed... I have V4 installed, it has been a long journey.

1. Originally I had KDE Plasma and in order to make this hyprland stuff to work I had to remove it completely because nothing else worked.
2. While trying to make this work with my NVIDIA card, I broke my GRUB and spend a few days doing research to fix it.
3. For some reason that I don't know, I could not boot from a bootable USB/DVD from the Arch Linux ISO (neither August and September 2023 worked), I was getting a very strange error posted above: amd gpio invalid config param 0014
4. I tried making a bootable USB from the current EndeavourOS ISO and I did not know their GRUB has an option to support NVIDIA, so I picked up this option.
5. Finally, I was able to boot from this live USB, and arch-chrooted and fixed GRUB.

**Comment by RealSnart** [comment]
I have the same problem. Installed some new updates after which I can't login anymore. Login -> blackscreen -> back to login. I thought I messed sth up so I tried to reinstall it but I still have the same problem. Does someone have a fix?

**Comment by charisvt** [comment]
My guess is a new Hyprland update probably messed up the compatibility with one or more of the packages. I will try to manually setup the individual packages after clean Hyprland to try to recreate this and find the culprit.

**Comment by gavski02** [comment]
Just installed fresh setup experiencing the same issue.

**Comment by LazKot** [comment]
> My guess is a new Hyprland update probably messed up the compatibility with one or more of the packages. I will try to manually setup the individual packages after clean Hyprland to try to recreate this and find the culprit.

I did this and found this issue reproduced at the install of the most current nvidia-dkms (535.104.05-1)

**Comment by TeddyHuang-00** [comment]
> I did this and found this issue reproduced at the install of the most current nvidia-dkms (535.104.05-1)

I have another fresh install of arch but this time using the bundled archinstaller, and choose hyprland with proprietary Nvidia drivers. It works fine until I installed `nvidia` or `nvidia-dkms` and then everything broke down and cannot get into the desktop anymore.

I think this is an upstream issue with `hyprland-nvidia` if all of you are using nvidia graphic card. Don't know if that's the case.

**Comment by charisvt** [comment]
After some testing I can confirm the issue is with the latest nvidia-dkms. You can manually force dkms to install an older nvidia proprietary driver but this is not a bug related to this project.

**Comment by LazKot** [comment]
> After some testing I can confirm the issue is with the latest nvidia-dkms. You can manually force dkms to install an older nvidia proprietary driver but this is not a bug related to this project. 

Charisvt, would you know what would be the best way of installing a previous version of the nvidia-dkms package?

**Comment by bojogkaret** [comment]
edit .config/hypr/env_var_nvidia.conf add line env = WLR_RENDERER_ALLOW_SOFTWARE,1

**Comment by bojogkaret** [comment]
edit .config/hypr/env_var_nvidia.conf add new line `env = WLR_RENDERER_ALLOW_SOFTWARE,1`

**Comment by TeddyHuang-00** [comment]
> edit .config/hypr/env_var_nvidia.conf add new line `env = WLR_RENDERER_ALLOW_SOFTWARE,1`

Confirm this is the solution to me. But I have to take an additional step to configure kernel parameter. For those who have the same issue, follow the official guide to figure out where you should put the configuration `nvidia_drm.modeset=1`: https://wiki.hyprland.org/Nvidia/ . For record, I also un-comment the two line in `.config/hypr/env_var_nvidia.conf` that is suggested by the official guide. Try this out if you are still getting problems.

**Comment by LazKot** [comment]
> edit .config/hypr/env_var_nvidia.conf add new line `env = WLR_RENDERER_ALLOW_SOFTWARE,1`

Can confirm this has solved my problem as well. Thank you @bojogkaret

**Comment by econsta** [comment]
> > edit .config/hypr/env_var_nvidia.conf add new line `env = WLR_RENDERER_ALLOW_SOFTWARE,1`
> 
> Confirm this is the solution to me. But I have to take an additional step to configure kernel parameter. For those who have the same issue, follow the official guide to figure out where you should put the configuration `nvidia_drm.modeset=1`: https://wiki.hyprland.org/Nvidia/ . For record, I also un-comment the two line in `.config/hypr/env_var_nvidia.conf` that is suggested by the official guide. Try this out if you are still getting problems.

This was working for me for several months, updated today and the issue has returned, now none of this works, any ideas?

**Comment by charisvt** [comment]
I can confirm that a recent nvidia update breaks this, I rerolled using timeshift. Any further fixes are welcome.

**Comment by Vishal-Rawat** [comment]
I was also having the same issue but it started working again after the latest update.

**Comment by AlphaSoundZ** [comment]
For me it worked after changing Kernel tilo the linux-zen Kernel, and then reinstalling the dkms, so it builds dir the new Kernel

**Comment by TeddyHuang-00** [comment]
The issue seems to be reoccurring sometimes. I had the same issue happening today after upgrading nvidia drivers, and then it magically worked after reinstalling the linux kernel. Try reinstalling your kernel if you met the same problem again.

**Comment by 0x3us4** [comment]
I managed to get it to work on nvidia using Nouveau Driver.
Use this repo instead.
I did a small change on driver installation.

https://github.com/0x3us4/HyprV4

@Vishal-Rawat @gavski02 @KhushalSharma-dev @LazKot @TeddyHuang-00 @charisvt @AlphaSoundZ @bojogkaret @t8go @BlakeDotCom
